<link rel="stylesheet" type="text/css" href="css.css">.
<?php

// defining the products in arrays
$product1 = array('number' => 1,
    'desc' => 'Chocolate Chip Bite Size cookies',
    'price' => 49.99);

$product2 = array('number' => 2,
    'desc' => 'Peanut Butter Cookies',
    'price' => 39.99);

$product3 = array('number' => 3,
    'desc' => 'SpongeBob Bite Size Cookies',
    'price' => 59.99);

$product4 = array('number' => 4,
    'desc' => 'SpongeBob Nickalodean Cookies',
    'price' => 29.99);

$product5 = array('number' => 5,
    'desc' => 'SpongeBob Cookie Cake',
    'price' => 44.99);

$product6 = array('number' => 6,
    'desc' => 'Chocolate Chip Large Cookie',
    'price' => 19.99);

$product7 = array('number' => 7,
    'desc' => 'Chocolate Chip Filled Cookies',
    'price' => 24.99);

$product8 = array('number' => 8,
    'desc' => 'Peanut Butter Cup Cookies',
    'price' => 29.99);

$product9 = array('number' => 9,
    'desc' => 'Peanut Butter Candy Cookies',
    'price' => 26.48);



// creating a product array to hold the infomration on individual products
$products = array($product1, $product2, $product3, $product4, $product5, $product6, $product7, $product8, $product9);
?>